name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Build core package first for dependency resolution
    - name: Build core package
      run: cd packages/core && npm run build

    - name: Wait for DynamoDB Local
      run: |
        echo "Waiting for DynamoDB Local to start..."
        for i in {1..60}; do
          if curl -s http://localhost:8000 > /dev/null 2>&1; then
            echo "DynamoDB Local is ready"
            # Test basic DynamoDB operation
            curl -X POST http://localhost:8000/ -H 'Content-Type: application/x-amz-json-1.0' -H 'X-Amz-Target: DynamoDB_20120810.ListTables' -d '{}'
            break
          fi
          echo "Attempt $i/60: DynamoDB Local not ready yet..."
          sleep 3
        done

    - name: Run integration tests
      run: npm run test:integration
      env:
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
        AWS_DEFAULT_REGION: ap-northeast-1
        NODE_ENV: test