name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Build core package first for dependency resolution
    - name: Build core package
      run: cd packages/core && npm run build

    - name: Wait for DynamoDB Local
      run: |
        echo "Waiting for DynamoDB Local to start..."
        for i in {1..60}; do
          if curl -s http://localhost:8000 > /dev/null 2>&1; then
            echo "DynamoDB Local is ready"
            break
          fi
          echo "Attempt $i/60: DynamoDB Local not ready yet..."
          sleep 3
        done

    - name: Create DynamoDB Tables
      run: |
        echo "Creating DynamoDB tables..."
        
        # FeatureFlags テーブル
        aws dynamodb create-table \
          --endpoint-url http://localhost:8000 \
          --table-name FeatureFlags \
          --billing-mode PAY_PER_REQUEST \
          --key-schema AttributeName=flagKey,KeyType=HASH \
          --attribute-definitions AttributeName=flagKey,AttributeType=S \
          --region ap-northeast-1 || true
        
        # TenantOverrides テーブル  
        aws dynamodb create-table \
          --endpoint-url http://localhost:8000 \
          --table-name TenantOverrides \
          --billing-mode PAY_PER_REQUEST \
          --key-schema AttributeName=tenantId,KeyType=HASH AttributeName=flagKey,KeyType=RANGE \
          --attribute-definitions AttributeName=tenantId,AttributeType=S AttributeName=flagKey,AttributeType=S \
          --region ap-northeast-1 || true
        
        # EmergencyControl テーブル
        aws dynamodb create-table \
          --endpoint-url http://localhost:8000 \
          --table-name EmergencyControl \
          --billing-mode PAY_PER_REQUEST \
          --key-schema AttributeName=controlType,KeyType=HASH AttributeName=flagKey,KeyType=RANGE \
          --attribute-definitions AttributeName=controlType,AttributeType=S AttributeName=flagKey,AttributeType=S \
          --region ap-northeast-1 || true
        
        echo "Tables created successfully"
        
        # テーブル確認
        aws dynamodb list-tables --endpoint-url http://localhost:8000 --region ap-northeast-1
      env:
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
        AWS_DEFAULT_REGION: ap-northeast-1

    - name: Run integration tests
      run: npm run test:integration
      env:
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
        AWS_DEFAULT_REGION: ap-northeast-1
        NODE_ENV: development
        STAGE: development
        DYNAMODB_ENDPOINT: http://localhost:8000
        FEATURE_FLAGS_TABLE_NAME: FeatureFlags